### ISSUE TITLE
Broken when run limit-single-line-comments with ignoreCommentsWithCode: true

### ISSUE THREAD

**Issue by yf-yang** [lasselupe33/eslint-plugin-comment-length#12]
Related: https://github.com/eslint/eslint/issues/16878

https://github.com/lasselupe33/eslint-plugin-comment-length/blob/1a381d6159f4b970e1091c7be04dde8cbcd1a3ff/rules/src/rules/limit-single-line-comments/root.ts#L82

ruleContext.parserPath is no longer supported in v9, so this option breaks eslint execution.

**Comment by lasselupe33** [comment]
Thanks for the report, @yf-yang

I'll take a look at this soon, but as mentioned in #10, it will likely be a couple of weeks before I get a chance to fix this. I'll keep you posted.

**Comment by lasselupe33** [comment]
This issue should be resolved with the latest major **v2** release of this plugin.

Please feel free to re-open this issue if you still encounter any issues.
