### ISSUE TITLE
Invalid types

### ISSUE THREAD

**Issue by jaydenseric** [lasselupe33/eslint-plugin-comment-length#14]
Very excited to be adding this plugin back into our project now that it supports ESLint v9, but have run into a problem where the published types have invalid module syntax in them, resulting in 141 errors in 36 files, like this:

```
node_modules/eslint-plugin-comment-length/src/const.message-ids.ts:1:1 - error TS1287: A top-level 'export' modifier cannot be used on value declarations in a CommonJS module when 'verbatimModuleSyntax' is enabled.

1 export enum MessageIds {
  ~~~~~~

node_modules/eslint-plugin-comment-length/src/const.message-ids.ts:6:1 - error TS1287: A top-level 'export' modifier cannot be used on value declarations in a CommonJS module when 'verbatimModuleSyntax' is enabled.

6 export const reportMessages = {
  ~~~~~~

node_modules/eslint-plugin-comment-length/src/index.ts:3:10 - error TS1286: ESM syntax is not allowed in a CommonJS module when 'verbatimModuleSyntax' is enabled.

3 import { limitMultiLineCommentsRule } from "./rules/limit-multi-line-comments/rule";
           ~~~~~~~~~~~~~~~~~~~~~~~~~~

node_modules/eslint-plugin-comment-length/src/index.ts:4:10 - error TS1286: ESM syntax is not allowed in a CommonJS module when 'verbatimModuleSyntax' is enabled.

4 import { limitSingleLineCommentsRule } from "./rules/limit-single-line-comments/rule";
           ~~~~~~~~~~~~~~~~~~~~~~~~~~~
```

It's not correct to set the module resolution to "bundler" in the TS Config of something that's published, like this package. It should be `nodenext`, which is the most correct mode for modern Node.js. Users will not be using a bundler to generate their ESLint config module; all the code and types need to be correct for runtime Node.js.

https://github.com/lasselupe33/eslint-plugin-comment-length/blob/75b5605ba1e54b126f7f45f789030437c938b36e/tsconfig.json#L20

Our project `tsconfig.json` is like this:

```json
{
  "$schema": "https://json.schemastore.org/tsconfig",
  "compilerOptions": {
    "allowJs": true,
    "forceConsistentCasingInFileNames": true,
    "verbatimModuleSyntax": true,
    "maxNodeModuleJsDepth": 10,
    "module": "nodenext",
    "noEmit": true,
    "strict": true,
    "target": "es2022"
  },
  "typeAcquisition": {
    "enable": false
  },
  "include": ["**/.*", "**/*"],
  "exclude": ["dist"]
}
```

And we have a `eslint.config.mjs` file with a `// @ts-check` comment at the top.

**Comment by lasselupe33** [comment]
Hey @jaydenseric, I appreciate the quick feedback and the detailed bug report.

It makes perfect sense that "Bundler" cannot be used as the "moduleResolution" for this library, I simply gave the tsconfig too little thought during the upgrade.. :) This has been corrected to "NodeNext" and I believe that **v2.1.0** should resolve the typings issue.
